#!/usr/bin/env bash
#SBATCH --job-name=HISZ_StdBootstrap
#SBATCH --partition=long
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64              # use all CPUs on your nodes
#SBATCH --mem=256G
#SBATCH --mail-user=rwl2@st-andrews.ac.uk
#SBATCH --mail-type=END,FAIL
#SBATCH --output=HISZ_27Nov.out
#SBATCH --error=HISZ_27Nov.err

# -------------------------------
# Conda activation
# -------------------------------
source /mnt/apps/users/rlouden/conda/etc/profile.d/conda.sh
conda activate iqtree_env

echo "Running on: $(hostname)"
echo "Using CPUs: $SLURM_CPUS_PER_TASK"
echo "Conda environment: $CONDA_DEFAULT_ENV"
iqtree --version
which iqtree

# -------------------------------
# Run IQ-TREE (STANDARD BOOTSTRAP)
# -------------------------------
iqtree \
  -s HisZ27Nov1.fasta \
  -m Q.PFAM+F+R10 \
  -b 1000 \                  # Standard bootstrap
  -alrt 1000 \               # SH-aLRT (optional, can remove)
  -nt $SLURM_CPUS_PER_TASK \
  -pre HISZ_StdBootstrap_27Nov
